/**
  *
  * Stanford Homesite 2017: Legacy JS Libs
  *
  * @since 1.0.0 built on 12-14-2022
  *
  * DO NOT EDIT THIS JS FILE DIRECTLY. IT IS GENERATED BY GRUNT.
  * -------------------------------------------------------------
  * See the js directory and edit the source files in the "libs"
  * directory of this folder.
  *
  */

