/**
 *
 * Module: grunt-contrib-concat
 * Documentation: https://npmjs.org/package/grunt-contrib-concat
 *
 */

module.exports = {

	libs: {
		options: {
			banner:
			'/**\n' +
			'  *\n' +
			'  * Stanford Homesite 2017: Legacy JS Libs\n' +
			'  *\n' +
			'  * @since <%= pkg.version %> built on <%= grunt.template.today("mm-dd-yyyy") %>\n' +
			'  *\n' +
			'  * DO NOT EDIT THIS JS FILE DIRECTLY. IT IS GENERATED BY GRUNT.\n' +
			'  * -------------------------------------------------------------\n' +
			'  * See the js directory and edit the source files in the "libs"\n' +
			'  * directory of this folder.\n' +
			'  *\n' +
			'  */\n\n'
		},
		src: [

			// Any external libraries would go here? Maybe?
			// '<%= pkg._componentpath %>/js/sprintf.js',
			// '<%= pkg._componentpath %>/js/custom.js',
			// '<%= pkg._npmpath %>/handlebars/dist/handlebars.runtime.js',
			// '<%= pkg._npmpath %>/packery/dist/packery.pkgd.js'

		],
		dest: '<%= pkg._themepath %>/js/libs.js'
	}

};
